awesome-algorand/awesome-algorand

- README.md
> Add Visitors and CI markdown badges

- README.md
- Fixing multiple typos
- Adding learning section
> Adding Learning Section; Fixing typos

- .github/workflows/ci.yaml
- .github/workflows/website-deploy.yaml
- README.md
- Adding new website available at awesomealgo.com to aid getting traction and new contributors
- Various tweaks to configure CI to make this auto-deployable
> Improvement: Adding gh hosted website with jekyl and custom domain 🎉 

- README.md
[minter](https://github.com/algofishexe/minter) - Bulk mint Algorand NFTs following the ARC-69 community standard. Written in Node.js by [@fish.exe](https://twitter.com/AlgofishExe).
> Add minter by fish.exe

- README.md
This adds a link to the VSCode extension made by [Obsidian Labs](https://github.com/ObsidianLabs).
> Add vscode-algorand by Obsidian Labs

- README.md
> Add more Algorand `SDKs` and other links

- README.md
Fixes typo as per issue report: https://github.com/aorumbayev/Awesome-Algorand/issues/15
> Fixing duplicated howbigisalgo link

- README.md
The Biggest Unofficial One-Stop Hub for Algorand
> Add `Algocurator`, an Unofficial Algorand resource hub

- README.md
Adds web 3.0 version of awesomealgo domain as a backup for `.app` domain. Will work in redirect mode for now, will have a separate deployment step in CI later.
> Adding web 3.0 hosted `.crypto` domain 🎉

- README.md
> Adding missing header into readme

- README.md
Added links to the Tinyman Python SDK and Algofi's Python and JavaScript SDKs.
> Add `Tinyman` and `Algofi` `SDK`s

- README.md
New section for nodes
- Algorand - The Undocumented Docs
- AlgoNode
> Adding `algorand-undoc-docs` and `algonode`

- README.md
> Adding `genpyteal`

- README.md
Adding info on ARC69 community convention. 
> Adding `ARC69`

- README.md
Metrics tab
Added tutorials
Added examples for JS SDK (easy for devs to find relevant examples)
Added ZestBloom digital art NFT marketplace
Added ANS
> Add multiple projects

- README.md
Addressing the following issue -> https://github.com/aorumbayev/Awesome-Algorand/issues/27
N/A
> Adjusting `Metrics` section

- .github/workflows/ci.yaml
- .github/workflows/website-deploy.yaml
- ARCHIVED.md
- README.md
Introduces a set of further tweaks and refinements in repository to address and comply with `awesome` repo and listing `Awesome Algorand` as part of the main `awesome` repo. 
> https://github.com/sindresorhus/awesome/pull/2165
Changes include: 
- Removed build badge (compliance requirement)
- Added .md file for storing archived projects (for future) 
- Removing all level 2 nested items from TOC (compliance requirement) 
- Addressing all `awesome-github` `double-link` linter warnings from `awesome-lint`
- Grammar and punctuation tweaks for entire README markdown
- Removing `Contributing` and `License` from TOC
---
</div>
> Complying readme with awesome repo requirements

- README.md
Allows debugging TEAL files inside VSCode. 
> Adding `teal-debugger-extension`

- README.md
Adding `algogator` a portfolio tracker webapp for Algorand wallets.
> Add `algogator`

- README.md
- Update Algogator title and add built by link
- Fix general grammar issue (build by -> built by)
-   ✅ Update readme.md
> Update  `Algogator` description

- README.md
Adds reach and aqua-compiler under new subsection under tools section dedicated to smart contracts
> Add `Smart Contracts` sub section

- README.md
Removing all warning silencers for awesome-lint compliance.
> Removing all `awesome-lint` silencers

- README.md
AlgoML (after Algorand Modelling Language) is a DSL for specifying Algorand smart contracts, which compiles into TEAL scripts.
> Adding `algoml`

- README.md
Add Algorand School crash course slide deck project.
> Add Algorand School community project.

- README.md
Moving `Algorand School` under `Learning` section (introducing a new `Crash Courses` subsection).
> Moving `Algorand School` under `Learning` section.

- README.md
Reflect latest changes in renaming of the wallet
Algorand Wallet was recently renamed to Pera wallet. This PR reflects that change
> Update `Algorand Wallet` to `Pera` wallet

- README.md
- Add GlitterFinance Bridge
- Add good old QRCode generator tool project
> Add GlitterFinance Bridge

- README.md
> ASA Stats moved to Portfolio Trackers Category

- README.md
Add Algorand Sandbox Dev Docker Hub image among Docket tools.
> Add Algorand Sandbox Dev to Docker tools

- README.md
Adding "Zero to Hero PyTeal" crash course in Learning section.
> Add `Zero to Hero PyTeal` crash course

- README.md
- Rename #Development-JavaScript to #Development-JavaScript/TypeScript 
- Add algo-builder and algo-builder-templetes.
-   [ ] Add `algo-builder`
-   [ ] Add `algo-builder-templetes`
Please review my PR. Thanks!
> add algo builder to development list

- README.md
Adding alpha vue 3 implementation of algofractals.com
> Adding `algofractals`

- README.md
> Add Tealang project

- README.md
-   [ ] Algorand discord server.
> Algorand Discord server

- README.md
> Adding `algorewards` governance calculator

- README.md
- [algorand.dev] (https://algorand.dev/) - Algorand Developer: The unofficial developer resource. 
- [daotools] (https://daotools.org/) - Manage all your DAO voting sessions in one Dapp.
- [ptokens](https://dapp.ptokens.io/swap?asset=btc&from=btc&to=algorand) - pNetwork Officially Launched Cross-Chain Bridges for Algorand
-   [ x] My code follows the [contribution guidelines](../CONTRIBUTING.md) of this project
-   [ x] This pull request has a title in the format `Add Name of Resource`:
> ⚠️ PLEASE NOTE - Do not expect a prompt review for your PR unless you have truthfully went over contribution guidelines, filled the PR description correctly AND most …
> Add 2 new Tools and 1 new bridge

- README.md
Added FORUM to Projects
Added FORUM a proof-of-stake social network on Algorand
-   [✅] My code follows the [contribution guidelines](../CONTRIBUTING.md) of this project
-   [✅] This pull request has a title in the format `Add Name of Resource`:
> Add 'FORUM'

- README.md
React.js based component library for rapid dapp deployment. Recipient of Algo dev grant. https://algorand.foundation/news/headline-inc-development-award
✅Please make sure you reviewed the checklist and comply with each requirement:_
-   [✅ ] My code follows the [contribution guidelines](../CONTRIBUTING.md) of this project
-   [✅ ] This pull request has a title in the format `Add Name of Resource`:
> ⚠️ PLEASE NOTE - Do not expect a prompt review for your PR unless you have truthfully went over contribution guidelines, filled the PR description correctly AND most importantly your changes are passing linters in [GitHub Actions …
> Add 'Pipeline-UI'

- README.md
[The New Computer Corporation](https://ncc.la/) loves Algorand and has live (The Song that Owns Itself - STOI) and in-development projects built on the network. We've also built and maintain a few open source tools (algonaut.js and irulan) that make these projects possible.
NCC projects: algonaut.js, Irulan, STOI
> ⚠️ PLEASE NOTE - Do not expect a prompt review for your PR unless you have truthfully went over contribution guidelines, filled the PR description correctly AND most importantly your …
> Add NCC projects

- README.md
Free and trustless ASA swapper, powered by Algorand ⚡️
> Add `AlgoWorld-Swapper`

- README.md
Adding a link to the new ARC website.
-   [X] My code follows the [contribution guidelines](../CONTRIBUTING.md) of this project
-   [X] (**IMPORTANT**) This pull request title **must** have title in the following format `Name of Resource`:
-   [X] I am aware that the PR title will be used as part of the automated tweet that will be sent on behalf of `@millionalgos` once this PR is merged. 
- For your reference, the tweet message is assembled as follows:
``` 
"⭐️ Check out ${{ …
```
> ARC website arc.algorand.foundation

- README.md
Add Dappflow to chain explorers. Dappflow is extremely useful _off-the-shelf_ explorer for private networks that works even in `localhost` with Sandbox.
-   [x] I am aware that the PR title will be used as part of the …
> Dappflow, private network explorer

- README.md
Add Smart ASA PyTeal reference implementation based on ARC-20.
-   [X] My code follows the [contribution guidelines](../CONTRIBUTING.md) of this project
-   [X] (**IMPORTANT**) This pull request title **must** have title in the following format `Name of Resource`:
-   [X] I am aware that the PR title will be used as part of the automated tweet that will be sent on behalf of `@millionalgos` once this PR is merged. 
- For …
> Smart ASA reference implementation

- README.md
ASC Builder is a GUI smart contracts development tool that consists of a developer-friendly interface comprising of widgets,
components and configuration parameters that aid in a seamless workflow from start to finish which will in turn be compiled to PyTEAL source code.
- …
> ASC Builder

- README.md
- For your reference, the tweet message is assembled as follows:
``` …
```
> SubQuery Indexer

- README.md
Tweaking languages sections.
Adding TEALrb.  …
> TEALrb - A Ruby DSL for writing ASCs

- README.md
- Initial chunk of companies providing security audits for Algo contracts.
-   [x] I am aware that the PR title will be used as part of the automated tweet that will be sent on behalf of `@millionalgos` once this PR is …
> New section on security auditing companies

- .gitignore
- README.md
Adding formal verification tools for smart contracts.
- For your …
> AVM Semantics

- README.md
Adding an introduction to AVM and Applications under **Crash Courses** section.
An introduction to AVM and Applications under **Crash Courses** section from the International School on Algorand Smart Contracts.
-   [x] I am …
> Introduction to AVM and Applications

- README.md
New section for absolute beginners to provide a good prerequisite information that can aid with learning more about algorand specific blockchain technologies
-   [ ] I am aware that the PR title will be used as part of the …
> Foundations of Blockchains lectures by Tim Roughgarden

- README.md
> [no-tweet] updating badges

- README.md
Add 'PyTeal ABI Smart Contracts' video lecture.
- For your reference, the tweet message is assembled as follows:
``` 
"⭐️ Check out ${{ …
```
> PyTeal ABI Smart Contracts

- README.md
Add `Beaker` to Crash Courses section: a Python framework for Algorand Smart Contract.
- For your reference, the tweet message is assembled …
> Beaker - Algorand Smart Contract Python framework

- README.md
Adding algoping
- For your reference, the tweet message is assembled as …
> AlgoPing - tiny health checking bot for Algorand nodes

- README.md
Adding algorand-ecosystem-audits
- For your reference, the tweet message …
> algorand-ecosystem-audits collection by blockshake.io

- README.md
Adding vs code extension
- For your reference, the tweet message is …
> Algorand Visual Studio extension

- README.md
feat: Added the article, Dissecting Algorand (https://medium.com/coinmonks/dissecting-algorand-e962f48f8c72) to the Crash Courses
Dissecting Algorand is an overview of Algorand's inner workings. It reviews VRF's, the consensus protocol (Pure Proof of Stake), fee structure, languages used in DApp development, the way nodes communicate, and the storage used for each node and the indexer.  At the end it compares Algorand with other networks based on the Blockchain Trilemma. 
-   ✅ …
> Dissecting Algorand - a medium article by Mabel Oza

- README.md
Tweaking readme
- For your reference, the tweet message is assembled as …
> [no-tweet] restoring repo rooster

- README.md
[Messina](https://messina.one/) - The ALGO — ETH two-way Messina.one's Bridge will open the doors for interoperability between Ethereum and ERC-20 tokens with Algorand.
The ALGO — ETH two-way Messina.one's Bridge will open the doors for interoperability between Ethereum and ERC-20 tokens with Algorand.
-   [x ] My code follows the [contribution guidelines](../CONTRIBUTING.md) of this project
-   [x ] (**IMPORTANT**) This pull request title **must** have title in the following format `Name of Resource`:
-   ✅ `py-algorand-sdk, pyteal and tinyman-py-sdk` …
> Messina One

- README.md
Adding cometa defi
- For your reference, the tweet message is assembled …
> Cometa.farm

- README.md
Adding algojig
- For your reference, the tweet message is assembled as …
> Algojig - a testing framework for smart contract from the team behind Tinyman

- README.md
- For your reference, the tweet message is …
> AlgoRealm UI - A web based console emulator for playing AlgoRealm

- README.md
- For your reference, the tweet message is …
> Add ASA.cafe to the list of NFT Marketplaces

- README.md
minor changes in structure
- For your …
> [no-tweet] minor refresh in md structure

- README.md
> Bitquery.io - Actionable, insightful blockchain GraphQL APIs for more than 30 blockchains

- README.md
> Defly Wallet - Algorand wallet with great suit of integrated DeFi features.

- README.md
Adding exodus
- For your reference, the tweet …
> Exodus - a multi-cryptocurrency wallet that supports Algorand

- README.md
> Defly-connect - JavaScript SDK for integrating Defly Wallet to web applications.

- README.md
> SliceSwap - one place to trade your assets across major Algorand Dex's. 

- README.md
Adding algokit
- For your reference, the tweet …
> AlgoKit CLI - the one-stop shop tool for developers building on the Algorand network

- README.md
Add Pera Explorer to explorer section
- For …
> Pera Explorer - Search any ASA, NFT or account on Algorand

- README.md
> Daffi Wallet - an Algorand blockchain wallet client with integrated access to Daffi platform

- .github/workflows/website-deploy.yaml
- README.md
- markdown/algohelp.md
Adding tealdebugger by hipo labs
> TealInspector - quick and easy TEAL error debugging by Hipo Labs

- .github/workflows/website-deploy.yaml
- README.md
> Beaker-ts - generate typescript clients for your beaker dapps

- .gitignore
- README.md
</div>
<br/>
-   [x ] My code follows the [contribution guidelines](../CONTRIBUTING.md) of this project
-   [ x] (**IMPORTANT**) This pull request …
> .NET - adds 4 new references under .NET category with current SDK, project SDKs, and PowerShell module.

- README.md
</div>
<br/>
-   [x] (**IMPORTANT**) This pull request …
>  Pera Web Wallet - Pera Wallet is now available.

- README.md
</div>
<br/>
[![](https://mermaid.ink/img/pako:eNplUstu2zAQ_JUFL0mBuL370EKRH80hQeD20KAqkI24lojyIZBUBEHyv3cpxbGC6kTN7s7MPgZROkliLSqPTQ0_N4UF_rLfT679A6vV1zG0L0bFAI-HEW6vG08NeoKj8-DpVVH3aa64TcmQDxkHe9cWjJbORq9e2qhsBQmIDrKOgjOU6coliFnS8zvp5ttpJson1TM6wmbIpCTJao0LKjrfMw-XXhn0f6Xr7Bfk3JpzPxt5BUel6Uy1maieKIzw6_pAKPuFb6bADlX8v5W57MGx9gdLF-sjbIf7HnIeHZdr7bowNbjsLn_v3tkpWLVKklaWQpK2Eh …
> [unreal-algorand-sdk] - https://github.com/Wisdom-Labs/Algorand-Unreal-Engine-SDK

- README.md
</div>
<br/>
[![](https://mermaid.ink/img/pako:eNplUstu2zAQ_JUFL0mBuL370EKRH80hQeD20KAqkI24lojyIZBUBEHyv3cpxbGC6kTN7s7MPgZROkliLSqPTQ0_N4UF_rLfT679A6vV1zG0L0bFAI-HEW6vG08NeoKj8-DpVVH3aa64TcmQDxkHe9cWjJbORq9e2qhsBQmIDrKOgjOU6coliFnS8zvp5ttpJson1TM6wmbIpCTJao0LKjrfMw-XXhn0f6Xr7Bfk3JpzPxt5BUel6Uy1maieKIzw6_pAKPuFb6bADlX8v5W57MGx9gdLF-sjbIf7HnIeHZdr7bowNbjsLn_v3tkpWLVKklaWQpK2Eh …
> Adding Algorand's Conduit repo

- README.md
</div>
<br/>
[![](https://mermaid.ink/img/pako:eNplUstu2zAQ_JUFL0mBuL370EKRH80hQeD20KAqkI24lojyIZBUBEHyv3cpxbGC6kTN7s7MPgZROkliLSqPTQ0_N4UF_rLfT679A6vV1zG0L0bFAI-HEW6vG08NeoKj8-DpVVH3aa64TcmQDxkHe9cWjJbORq9e2qhsBQmIDrKOgjOU6coliFnS8zvp5ttpJson1TM6wmbIpCTJao0LKjrfMw-XXhn0f6Xr7Bfk3JpzPxt5BUel6Uy1maieKIzw6_pAKPuFb6bADlX8v5W57MGx9gdLF-sjbIf7HnIeHZdr7bowNbjsLn_v3tkpWLVKklaWQpK2Eh …
> Grid - Configurable Lightweight Static Site for Displaying Zestbloom Supported Contracts

- README.md
</div>
<br/>
Adding the TEALScript repository
[![](https://mermaid.ink/img/pako:eNplUstu2zAQ_JUFL0mBuL370EKRH80hQeD20KAqkI24lojyIZBUBEHyv3cpxbGC6kTN7s7MPgZROkliLSqPTQ0_N4UF_rLfT679A6vV1zG0L0bFAI-HEW6vG08NeoKj8-DpVVH3aa64TcmQDxkHe9cWjJbORq9e2qhsBQmIDrKOgjOU6coliFnS8zvp5ttpJson1TM6wmbIpCTJao0LKjrfMw-XXhn0f6Xr7Bfk3JpzPxt5BUel6Uy1maieKIzw6_pAKPuFb6bADlX8v5W57MGx9gdLF-sjbIf7HnIeHZdr7bowNbjsLn_v3tkpWLVKklaWQpK2EhoMIY0mvzsb3l4M74bHA6gAUUXN3c8qnD3Ns …
> TEALScript - Enables Algorand smart contract development with native TypeScript syntax, tooling, and IDE support

- README.md
Added Vantage Point Blockchain as an auditing services provider for Algorand ecosystem under Security Auditing Services with details in README.md
</div>
<br/>
<details><summary>Option 2. Text guideline 📜</summary>
> ⚠️ PLEASE NOTE - Do not expect a prompt review for your PR unless you have truthfully went over contribution guidelines, filled the PR description correctly AND most importantly your changes are passing linters in [GitHub …
> Vantage Point Blockchain - Smart Contract Audits, Crypto Wallet Audits and Penetration Testing services provider

- .github/pull_request_template.md
- README.md
</div>
<br/>
Addin ceal
---
[![](https://mermaid.ink/img/pako:eNplUstu2zAQ_JUFL0mBuL370EKRH80hQeD20KAqkI24lojyIZBUBEHyv3cpxbGC6kTN7s7MPgZROkliLSqPTQ0_N4UF_rLfT679A6vV1zG0L0bFAI-HEW6vG08NeoKj8-DpVVH3aa64TcmQDxkHe9cWjJbORq9e2qhsBQmIDrKOgjOU6coliFnS8zvp5ttpJson1TM6wmbIpCTJao0LKjrfMw-XXhn0f6Xr7Bfk3JpzPxt5BUel6Uy1maieKIzw6_pAKPuFb6bADlX8v5W57MGx9gdLF-sjbIf7HnIeHZdr7b …
> CEAL - C to Algorand TEAL compiler

- README.md
> [DirectoryDotAlgo.xyz] - Algorand's unofficial ecosystem directory

- README.md
</div>
<br/>
Adding the stake.tax Python repository under open source projects.
---
[![](https://mermaid.ink/img/pako:eNplUstu2zAQ_JUFL0mBuL370EKRH80hQeD20KAqkI24lojyIZBUBEHyv3cpxbGC6kTN7s7MPgZROkliLSqPTQ0_N4UF_rLfT679A6vV1zG0L0bFAI-HEW6vG08NeoKj8-DpVVH3aa64TcmQDxkHe9cWjJbORq9e2qhsBQmIDrKOgjOU6coliFnS8zvp5ttpJson1TM6wmbIpCTJao0LKjrfMw-XXhn0f6Xr7Bfk3JpzPxt5BUel6Uy1maieKIzw6_pAKPuFb6bADlX8v5W57MGx9gdLF-sjbIf7HnIeHZdr7bowNbjsLn_v3t …
> StakeTax - Algorand DeFi tax CSVs

- .github/pull_request_template.md
</div>
<br/>
N/A - noticed a stale link while creating #137 
---
[![](https://mermaid.ink/img/pako:eNplUstu2zAQ_JUFL0mBuL370EKRH80hQeD20KAqkI24lojyIZBUBEHyv3cpxbGC6kTN7s7MPgZROkliLSqPTQ0_N4UF_rLfT679A6vV1zG0L0bFAI-HEW6vG08NeoKj8-DpVVH3aa64TcmQDxkHe9cWjJbORq9e2qhsBQmIDrKOgjOU6coliFnS8zvp5ttpJson1TM6wmbIpCTJao0LKjrfMw-XXhn0f6Xr7Bfk3JpzPxt5BUel6Uy1maieKIzw6_pAKPuFb6bADlX8v5W57MGx9gdLF-sjbIf7HnIeHZdr7bowNbjsLn_v3tkpWLVKklaWQpK2EhoMI …
> [no-tweet] fix PR template contributing link.

- README.md
- Adding algokit community template for tealish and algojig
> algokit-tealish-template - AlgoKit community template for Tealish and Algojig

- README.md
> AlgoNode - Free Node/Indexer APIs, Node running FAQ, and daily snapshots.

- README.md
> AwesomeAlgo Search 0.1.0 - cross platform Algorand ecosystem AI search client

- ARCHIVED.md
- README.md
</div>
<br/>
Adding voting tooling from Algorand Foundation and vote-coin project by @EAlgonaut.
---
[![](https://mermaid.ink/img/pako:eNplUstu2zAQ_JUFL0mBuL370EKRH80hQeD20KAqkI24lojyIZBUBEHyv3cpxbGC6kTN7s7MPgZROkliLSqPTQ0_N4UF_rLfT679A6vV1zG0L0bFAI-HEW6vG08NeoKj8-DpVVH3aa64TcmQDxkHe9cWjJbORq9e2qhsBQmIDrKOgjOU6coliFnS8zvp5ttpJson1TM6wmbIpCTJao0LKjrfMw-XXhn0f6Xr7 …
> [New section] On-chain voting tools powered by Algorand

- README.md
</div>
<br/>
Adding AWallet, Aramid.Finance, Stabilitias.Finance by EAlgonaut
---
[![](https://mermaid.ink/img/pako:eNplUstu2zAQ_JUFL0mBuL370EKRH80hQeD20KAqkI24lojyIZBUBEHyv3cpxbGC6kTN7s7MPgZROkliLSqPTQ0_N4UF_rLfT679A6vV1zG0L0bFAI-HEW6vG08NeoKj8-DpVVH3aa64TcmQDxkHe9cWjJbORq9e2qhsBQmIDrKOgjOU6coliFnS8zvp5ttpJson1TM6wmbIpCTJao0LKjrfMw-XXhn0f6Xr7Bfk3JpzPxt5BUel6Uy1 …
> New listings: AWallet, Aramid.Finance, Stabilitas.Finance

- README.md
</div>
<br/>
Adding vestige.fi
---
[![](https://mermaid.ink/img/pako:eNplUstu2zAQ_JUFL0mBuL370EKRH80hQeD20KAqkI24lojyIZBUBEHyv3cpxbGC6kTN7s7MPgZROkliLSqPTQ0_N4UF_rLfT679A6vV1zG0L0bFAI-HEW6vG08NeoKj8-DpVVH3aa64TcmQDxkHe9cWjJbORq9e2qhsBQmIDrKOgjOU6coliFnS8zvp5ttpJson1TM6wmbIpCTJao0LKjrfMw-XXhn0f6Xr7Bfk3JpzPxt5BUel6Uy1maieKIzw6_pAKPuFb6bADlX8v5W57MGx9gdLF-sjbIf7HnI …
> Vestige.fi - real time tracking, charting and portfolio tracking on Algorand

- README.md
> AlgoRun - Simple CLI utility for setting up and starting Algorand MainNet participation node

- README.md
</div>
<br/>
- Adding goracle algokit templates
---
[![](https://mermaid.ink/img/pako:eNplUstu2zAQ_JUFL0mBuL370EKRH80hQeD20KAqkI24lojyIZBUBEHyv3cpxbGC6kTN7s7MPgZROkliLSqPTQ0_N4UF_rLfT679A6vV1zG0L0bFAI-HEW6vG08NeoKj8-DpVVH3aa64TcmQDxkHe9cWjJbORq9e2qhsBQmIDrKOgjOU6coliFnS8zvp5ttpJson1TM6wmbIpCTJao0LKjrfMw-XXhn0f6Xr7Bfk3JpzPxt5BUel6Uy1maieKIzw6_pAKPuFb6bADlX8v5W57M …
> AlgoKit Goracle template - quick start a goracle-enabled smart contract project in AlgoKit

- README.md
</div>
<br/>
Adding new algokit templates
---
[![](https://mermaid.ink/img/pako:eNplUstu2zAQ_JUFL0mBuL370EKRH80hQeD20KAqkI24lojyIZBUBEHyv3cpxbGC6kTN7s7MPgZROkliLSqPTQ0_N4UF_rLfT679A6vV1zG0L0bFAI-HEW6vG08NeoKj8-DpVVH3aa64TcmQDxkHe9cWjJbORq9e2qhsBQmIDrKOgjOU6coliFnS8zvp5ttpJson1TM6wmbIpCTJao0LKjrfMw-XXhn0f6Xr7Bfk3JpzPxt5BUel6Uy1maieKIzw6_pAKPuFb6bADlX8v5W57MGx9gdL …
> New Official AlgoKit Templates

- README.md
> feat(learning-resource): ecosystem onboarding guide

- README.md
> [use-wallet-js] - TypeScript library for integrating Algorand wallets

- README.md
We went through the list and removed dead/unreachable projects. 
We also edited links and titles for projects that rebranded or changed their main URL.
Lastly, we added notes for GitHub repos that are now archived.
> [no-tweet] projects cleanup

- README.md
removing algosigner from wallets, adding lora to explorers
</div>
<br/>
---
[![](https://mermaid.ink/img/pako:eNplUstu2zAQ_JUFL0mBuL370EKRH80hQeD20KAqkI24lojyIZBUBEHyv3cpxbGC6kTN7s7MPgZROkliLSqPTQ0_N4UF_rLfT679A6vV1zG0L0bFAI-HEW6vG08NeoKj8-DpVVH3aa64TcmQDxkHe9cWjJbORq9e2qhsBQmIDrKOgjOU6coliFnS8zvp5ttpJson1TM6wmbIpCTJao0LKjrfMw-XXhn0f6Xr7Bfk3JpzPxt5BUel6Uy1maieKI …
> Lora - the explorer

- README.md
<a href="https://github.com/awesome-algorand/awesome-algorand"><img src="https://ipfs.algonode.xyz/ipfs/bafybeidwt23qadzoz77kxdvzj4pkmernr5e7pjzzge3rffn56ugibb2ojq"></a>
</div>
<br/>
fixing whitespace and adding tutorial and opensource code resources
_Review and comply with each requirement:_
> Only for official Algorand affiliates or platform teams
> Ensure your PR passes linters in [GitHub Actions pipeline](https://github.com/awesome-algorand/awesome-algorand/actions/workflows/ci.yaml) for prompt review.
Interested in discussing your contribution? [Sign up here](https://2c5n1ed3kz6.typeform.com/to/pAP5oPFx)
> fixing whitespace and adding resources

- README.md
Dappflow is no longer available. This PR replaces dappflow with Algosurf. 
_Review and comply with each requirement:_
> Blockchain Explorers - Add Algo Surf explorer
